minimum_pre_commit_version: "2.9.0"
repos:
  - repo: "https://github.com/psf/black"
    rev: "23.1.0"
    hooks:
      - id: "black"
        name: "Format code (black)"
        language_version: "python3"

  - repo: "https://github.com/timothycrosley/isort"
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: "python3"
        additional_dependencies: [toml]

  - repo: "https://github.com/pycqa/flake8"
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: "python3"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-json"
      - id: "check-toml"
      - id: "check-yaml"
      - id: "check-merge-conflict"

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "3.0.0"
    hooks:
      - id: shellcheck

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v2.4.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
